import { useEffect, useState } from "react";
import type { GitConflictFile, GitConflictWorkspace } from "@remote-ide/protocol";
import type { CoreClient } from "./client";

type Props = { client: CoreClient; initialPath: string; onClose(): void; onChanged(): void };
type View = "ours" | "base" | "theirs" | "result";

export function GitConflictWorkspaceDialog({ client, initialPath, onClose, onChanged }: Props) {
  const [workspace, setWorkspace] = useState<GitConflictWorkspace>(); const [path, setPath] = useState(initialPath); const [view, setView] = useState<View>("result"); const [draft, setDraft] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const file = workspace?.files.find((item) => item.path === path) ?? workspace?.files[0];
  useEffect(() => { void client.request("git.conflicts", {}).then((next) => { setWorkspace(next); setPath(next.files.some((item) => item.path === initialPath) ? initialPath : next.files[0]?.path ?? initialPath); }).catch((reason: unknown) => setError(message(reason))); }, [client, initialPath]);
  useEffect(() => { if (file) setDraft(file.result ?? ""); }, [file?.path, file?.result]);
  const resolve = async (result: string | null) => { if (!file) return; setBusy(true); setError(""); try { const next = await client.request("git.resolveConflict", { path: file.path, result }); setWorkspace(next); setPath(next.files[0]?.path ?? file.path); setView("result"); onChanged(); } catch (reason) { setError(message(reason)); } finally { setBusy(false); } };
  const act = async (action: "continue" | "abort") => { if (action === "abort" && !confirm(`Abort this ${workspace?.operation}? Git will return to its pre-operation state.`)) return; setBusy(true); setError(""); try { await client.request("git.conflictAction", { action }); onChanged(); onClose(); } catch (reason) { setError(message(reason)); } finally { setBusy(false); } };
  const shown = file ? view === "result" ? draft : file[view] ?? "(not present in this conflict)" : "All conflicted paths are resolved.";
  return <div className="dialog-overlay"><section className="conflict-workspace" role="dialog" aria-modal="true" aria-label="Git conflict resolution workspace"><header><div><h2>Resolve {workspace?.operation ?? "Git"} conflicts</h2><small>{workspace?.files.length ?? 0} unresolved path(s)</small></div><button title="Close conflict workspace" onClick={onClose}>×</button></header>{error && <div className="find-error" role="alert">{error}</div>}<div className="conflict-body"><nav aria-label="Conflicted paths">{workspace?.files.map((item) => <button className={item.path === file?.path ? "active" : ""} key={item.path} onClick={() => { setPath(item.path); setView("result"); }}>{item.path}</button>)}</nav><main>{file ? <><div className="conflict-versions">{(["ours", "base", "theirs", "result"] as View[]).map((item) => <button key={item} className={view === item ? "active" : ""} onClick={() => setView(item)}>{item}</button>)}</div>{view === "result" ? <textarea aria-label={`Resolution result for ${file.path}`} value={draft} onChange={(event) => setDraft(event.target.value)} /> : <pre aria-label={`${view} content for ${file.path}`}>{shown}</pre>}<footer><button disabled={busy || file.ours === undefined} onClick={() => void resolve(file.ours ?? "")}>Use ours</button><button disabled={busy || file.theirs === undefined} onClick={() => void resolve(file.theirs ?? "")}>Use theirs</button><button disabled={busy} onClick={() => void resolve(draft)}>Mark result resolved</button><button disabled={busy} onClick={() => void resolve(null)}>Resolve as deleted</button></footer></> : <p>Every path has been validated and staged. Continue when ready.</p>}</main></div>{workspace && <aside>{workspace.recovery}</aside>}<footer className="conflict-actions"><button disabled={busy || !workspace?.canAbort} onClick={() => void act("abort")}>Abort {workspace?.operation}</button><button disabled={busy || Boolean(workspace?.files.length) || !workspace?.canContinue} onClick={() => void act("continue")}>Continue {workspace?.operation}</button></footer></section></div>;
}

function message(reason: unknown): string { return reason instanceof Error ? reason.message : String(reason); }
