import { useEffect, useState } from "react";
import { Archive, RefreshCw, Trash2, X } from "lucide-react";
import type { GitStash, GitStashInclusion, GitStashPreview } from "@remote-ide/protocol";
import type { CoreClient } from "./client";
const defaults: GitStashInclusion = { staged: true, unstaged: true, untracked: false, ignored: false };
export function GitStashDialog({ client, selectedPaths, onClose, onChanged }: { client: CoreClient; selectedPaths: string[]; onClose(): void; onChanged(): void }) {
 const [stashes,setStashes]=useState<GitStash[]>([]),[preview,setPreview]=useState<GitStashPreview>(),[include,setInclude]=useState(defaults),[message,setMessage]=useState(""),[selectedOnly,setSelectedOnly]=useState(false),[busy,setBusy]=useState(false),[notice,setNotice]=useState("");
 const load=async()=>{ try { setStashes((await client.request("git.stashes",{})).stashes); } catch(e){setNotice(e instanceof Error?e.message:"Could not load stashes");} };
 useEffect(()=>{void load();},[]);
 const choose=async(stash:GitStash)=>{try{setPreview(await client.request("git.stashPreview",{reference:stash.reference}));setNotice("");}catch(e){setNotice(e instanceof Error?e.message:"Could not preview stash");}};
 const create=async()=>{setBusy(true);try{const {stash}=await client.request("git.createStash",{include,...(message.trim()?{message:message.trim()}:{}),...(selectedOnly?{paths:selectedPaths}:{})});await load();await choose(stash);onChanged();}catch(e){setNotice(e instanceof Error?e.message:"Could not create stash");}finally{setBusy(false);}};
 const apply=async(pop:boolean)=>{if(!preview||(pop&&!confirm(`Apply and permanently drop ${preview.stash.reference}? It is retained if applying fails.`)))return;setBusy(true);try{const r=await client.request(pop?"git.popStash":"git.applyStash",pop?{reference:preview.stash.reference,confirm:true}:{reference:preview.stash.reference});setNotice(r.outcome);await load();onChanged();}catch(e){setNotice(e instanceof Error?e.message:"Could not apply stash");}finally{setBusy(false);}};
 const drop=async()=>{if(!preview||!confirm(`Permanently drop ${preview.stash.reference}? This cannot be undone.`))return;setBusy(true);try{await client.request("git.dropStash",{reference:preview.stash.reference,confirm:true});setPreview(undefined);await load();}catch(e){setNotice(e instanceof Error?e.message:"Could not drop stash");}finally{setBusy(false);}};
 return <div className="dialog-overlay" onMouseDown={()=>!busy&&onClose()}><section className="stash-dialog" role="dialog" aria-modal="true" aria-label="Stash manager" onMouseDown={e=>e.stopPropagation()}><header><div><h2>Stash manager</h2><small>Choose exactly what to shelve.</small></div><button onClick={onClose}><X size={15}/></button></header><section><strong>Create stash</strong><input placeholder="Message (optional)" value={message} onChange={e=>setMessage(e.target.value)}/><div>{(["staged","unstaged","untracked","ignored"] as const).map(k=><label key={k}><input type="checkbox" checked={include[k]} disabled={k==="untracked"&&include.ignored} onChange={e=>setInclude(v=>({...v,[k]:e.target.checked,...(k==="ignored"&&e.target.checked?{untracked:true}:{})}))}/>{k}</label>)}</div><label><input type="checkbox" checked={selectedOnly} disabled={!selectedPaths.length} onChange={e=>setSelectedOnly(e.target.checked)}/>Selected paths only ({selectedPaths.length})</label><button disabled={busy} onClick={()=>void create()}><Archive size={14}/>Create stash</button></section><section><header><strong>Saved stashes</strong><button onClick={()=>void load()}><RefreshCw size={14}/></button></header>{stashes.map(s=><button key={s.reference} onClick={()=>void choose(s)}><code>{s.reference}</code> {s.message}</button>) || <p>No stashes.</p>}</section>{preview&&<section><strong>{preview.stash.reference}</strong><p>{preview.files.length} files. {preview.conflictRisk==="possible"?`Possible conflict with: ${preview.blockers.join(", ")}.`:"No overlapping current changes detected."}</p><small>{preview.recovery}</small><footer><button disabled={busy} onClick={()=>void apply(false)}>Apply (keep)</button><button disabled={busy} onClick={()=>void apply(true)}>Apply and drop</button><button className="danger" disabled={busy} onClick={()=>void drop()}><Trash2 size={14}/>Drop</button></footer></section>}{notice&&<p>{notice}</p>}</section></div>;
}
